version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - '3306'
    restart: always
    volumes:
      - /var/lib/mysql

  web:
    build: .
    # image: shasui2/portfolio-app:latest
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
     - .:/app
    ports:
      - "80:3000"
    depends_on:
      - db
    restart: always

  start_dependencies:
    build: .
    # image: shasui2/portfolio-app:latest
    depends_on:
      - db
    command: >
      /bin/bash -c "
        $PATH > echo
        while ! nc -z db 3306; do
          echo Database not ready;
          sleep 1;
        done;
        echo Database connected!;
      "