kind: Service
apiVersion: v1
metadata:
  name: portfolio-app-service
spec:
  type: NodePort
  selector:
    app: portfolio-app
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 3000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portfolio-app-deployment
  labels:
    app: portfolio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolio-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 3000